// Approved knowledge passages: the ONLY material the Caregiver Coach may answer from (REQ-AI-02).
// Each passage is plain language drawn from the claims register and the sub-study.
import { meta } from './activities';
import type { KnowledgePassage, Tier } from './types';

const k = (id: string, title: string, text: string, claims: string[], sections: string[], tier: Tier, keywords: string[]): KnowledgePassage =>
  ({ ...meta(claims, sections, tier), id, title, text, keywords });

export const KNOWLEDGE: readonly KnowledgePassage[] = [
  // --- Evidence basics
  k('K-01', 'Does music therapy help?', 'Music therapy from a credentialed music therapist probably helps overall functioning in the short term, with moderate certainty. Benefits show up most in engagement, parent-rated functioning and family quality of life.', ['C-001'], ['§3', '§3.1'], 'Verified', ['music therapy', 'help', 'evidence', 'work', 'effective', 'benefit', 'research']),
  k('K-02', 'What music therapy does not do', 'The largest careful trial found that music therapy on its own did not change core autism features on a standard clinical measure. It is best seen as an enjoyable add-on to core support such as speech therapy, not a replacement.', ['C-002', 'C-004'], ['§3', '§8'], 'Verified', ['core', 'severity', 'replace', 'instead', 'speech therapy', 'add-on', 'change autism']),
  k('K-03', 'Is it safe?', 'Music therapy is low risk. Trials report no increase in side effects, provided sound levels respect the child’s sensitivities.', ['C-003'], ['§3.1'], 'Verified', ['safe', 'safety', 'risk', 'side effects', 'harm']),
  k('K-04', 'Family-centred music', 'In family-centred music therapy, parents learn musical play for daily routines. Small trials found gains in social engagement at home and better parent–child relationships.', ['C-005', 'C-006'], ['§2', '§3'], 'Emerging', ['parent', 'family', 'home', 'routine', 'relationship']),
  k('K-05', 'Why music can suit autistic children', 'Many autistic children perceive pitch as well as or better than peers, and usually recognise happy, sad or scary music accurately. Songs are predictable, with repetition and a clear start and end, which may lower anxiety.', ['C-007', 'C-008', 'C-009'], ['§1', '§4'], 'Emerging', ['why', 'music', 'pitch', 'emotion', 'predictable', 'anxiety', 'like music']),
  // --- How-to: activities
  k('K-06', 'How much time', 'Ten to fifteen minutes a day of playful, shared music-making is a realistic and worthwhile goal. You do not need musical training.', ['C-012'], ['§7'], 'Emerging', ['how long', 'minutes', 'time', 'daily', 'every day', 'keep up', 'often', 'training', 'musical', 'sing badly', 'not musical']),
  k('K-07', 'Play together, not just listen', 'The benefit comes from making music together. Screens and background music are not therapy. Join in, copy your child, and take turns.', ['C-011'], ['§7.2'], 'Emerging', ['background music', 'as therapy', 'watch', 'videos', 'instead', 'screen', 'youtube', 'tablet', 'background', 'video', 'listen', 'tv']),
  k('K-08', 'Drum conversation', 'Sit facing your child with a drum or a box. First copy what they play. Then tap a short pattern, pause for 5–10 seconds and wait for a reply. Copy their reply. Keep pauses long, because waiting is the teaching moment.', ['C-005', 'C-010'], ['§7.1'], 'Emerging', ['drum', 'turn', 'turns', 'turn-taking', 'joint attention', 'conversation', 'copy', 'imitate']),
  k('K-09', 'Using pauses for requesting', 'Build up with "Ready, steady…" and pause before "GO!". Wait for a look, a sound or a word, then do the fun thing straight away. Any signal counts.', ['C-010'], ['§7.1'], 'Emerging', ['request', 'requesting', 'ask', 'pause', 'ready steady go', 'anticipation', 'wait']),
  k('K-10', 'Encouraging early words with songs', 'Sing a familiar song and leave out the last word, as in "Twinkle, twinkle, little…". Wait, accept any attempt, then sing the word clearly yourself.', ['C-010'], ['§7.1'], 'Emerging', ['words', 'more words', 'say', 'talk', 'speech', 'speak', 'language', 'fill in', 'first words', 'non-verbal', 'nonverbal']),
  k('K-11', 'Minimally verbal children and singing', 'Singing words while tapping a drum is a therapist-led approach that looks promising for some minimally verbal children in small studies. Larger trials are needed. Picture cards also help children who are not yet speaking to choose songs.', ['C-013', 'C-017'], ['§2', '§3', '§7.2'], 'Emerging', ['minimally verbal', 'non-verbal', 'nonverbal', 'not talking', 'aac', 'picture', 'singing', 'ammt']),
  k('K-12', 'Action songs for following instructions', 'Use action songs, such as "Head, shoulders, knees and toes", sung slowly with gestures. Show one action at a time and name it.', ['C-014'], ['§7.1'], 'Emerging', ['instructions', 'follow', 'listening', 'actions', 'action song', 'directions']),
  k('K-13', 'Routine songs', 'Use one short song for each routine (tidy-up, bath, teeth, leaving the house) and keep it the same every time. The repetition makes the routine predictable.', ['C-015'], ['§7.1'], 'Emerging', ['routine', 'transition', 'tidy', 'bath', 'teeth', 'brushing', 'leaving', 'bedtime', 'change activity']),
  k('K-14', 'Calm music for regulation', 'During calm-down time, use slow, quiet, familiar music. Rocking or swaying to the beat can help. Build a calm playlist your child chooses, and keep the volume moderate.', ['C-016'], ['§7.1', '§6.2'], 'Emerging', ['calm', 'meltdown', 'upset', 'regulate', 'regulation', 'settle', 'relax', 'sleep', 'bedtime', 'playlist']),
  k('K-15', 'Movement and rhythm', 'Marching, clapping, shakers and scarves to music are good for motor skills, because rhythm links sound and movement and may support coordination.', ['C-014'], ['§4', '§7.1'], 'Emerging', ['motor', 'movement', 'coordination', 'march', 'clap', 'dance']),
  k('K-16', 'Playing with siblings', 'Try simple band games: everyone plays, and everyone stops when the music stops. Keep groups small and predictable.', ['C-005', 'C-010'], ['§7.1'], 'Emerging', ['sibling', 'brother', 'sister', 'friends', 'peers', 'group', 'social']),
  k('K-17', 'Follow your child’s lead', 'Follow your child’s preferences. Some prefer instrumental music, some one favourite song on repeat. Start there, and celebrate participation, not performance.', ['C-018'], ['§7.2'], 'Emerging', ['favourite', 'favorite', 'same song', 'repeat', 'preference', 'refuses', 'not interested', 'walks away']),
  k('K-18', 'Picture choices', 'Picture cards for songs and instruments help children who are not yet speaking to take part. Let your child choose with a look, a point or a tap.', ['C-017'], ['§7.2'], 'Emerging', ['picture', 'cards', 'choose', 'choice', 'visual', 'aac']),
  // --- Sound sensitivity
  k('K-19', 'Sound sensitivity is common', 'Many autistic children find some everyday sounds distressing or painful, such as hand dryers, blenders, sirens, crying babies and crowded rooms. The aim is to protect your child from overload while gently building tolerance and control, never forcing exposure.', ['C-019', 'C-026'], ['§6'], 'Emerging', ['sound', 'noise', 'sensitive', 'sensitivity', 'hyperacusis', 'loud', 'ears', 'scream', 'screams', 'sudden noises', 'hand dryer', 'blender', 'toilet flush']),
  k('K-20', 'Hearing test', 'Arrange a hearing test with an audiologist experienced with autistic children, to rule out hearing loss or ear problems.', ['C-020'], ['§6.1'], 'Verified', ['hearing', 'audiologist', 'ears', 'test', 'deaf']),
  k('K-21', 'Sound diary', 'Keep a sound diary for 1–2 weeks: which sounds, where, how loud, and how your child reacted. Patterns, such as sudden, high-pitched or unexpected sounds, guide your plan.', ['C-021'], ['§6.1'], 'Verified', ['diary', 'track', 'pattern', 'triggers', 'record']),
  k('K-22', 'Occupational therapist', 'An occupational therapist (OT) can assess your child’s wider sensory profile.', ['C-022'], ['§6.1'], 'Verified', ['ot', 'occupational therapist', 'sensory', 'profile', 'assessment']),
  k('K-23', 'Ear defenders', 'Ear defenders or noise-cancelling headphones help in planned loud settings such as assemblies, shopping centres and fireworks. Using them all day may increase sensitivity over time, so use them for specific situations.', ['C-023'], ['§6.2'], 'Verified', ['ear defenders', 'headphones', 'noise cancelling', 'earmuffs', 'all day', 'fireworks', 'shopping']),
  k('K-24', 'Warnings and countdowns', 'Unpredictable sounds are usually the hardest. Give a warning and a countdown, such as "I’m going to use the blender in 3, 2, 1", and let your child press the button if they want to.', ['C-024'], ['§6.2'], 'Verified', ['warning', 'countdown', 'blender', 'vacuum', 'toilet', 'flush', 'predictable', 'surprise', 'sudden']),
  k('K-25', 'Control, choice and a "too loud" signal', 'Let your child control volume and choose music, offer a quiet retreat space, and agree a signal (a card or gesture) that means "too loud".', ['C-025'], ['§6.2'], 'Verified', ['control', 'choice', 'quiet space', 'too loud', 'signal', 'card', 'volume']),
  k('K-26', 'Graded practice with difficult sounds', 'Record a difficult sound and play it very softly during a favourite activity. Increase the volume in small steps over weeks, always within your child’s comfort, and stop if distress rises. In this app, practice only runs with a caregiver present and has built-in stop rules.', ['C-026'], ['§6.2'], 'Verified', ['exposure', 'graded', 'gradually', 'practice', 'practise', 'desensitise', 'desensitize', 'get used to', 'tolerate', 'tolerating', 'tolerance', 'vacuum', 'step by step']),
  k('K-27', 'Sound anchors', 'Familiar music or white noise at a moderate volume can mask background noise at bedtime or during homework.', ['C-027'], ['§6.2'], 'Verified', ['white noise', 'mask', 'homework', 'bedtime', 'background noise']),
  k('K-28', 'Explaining sounds', 'Social stories and visual explanations help explain what a sound is and why it happens, such as a fire alarm. Pair them with practice visits.', ['C-028'], ['§6.2'], 'Verified', ['social story', 'fire alarm', 'explain', 'visual', 'school']),
  k('K-29', 'Making loud sounds yourself', 'Making a loud sound yourself on a drum, with full control, is often less threatening than hearing it unexpectedly. This can be a gentle bridge to tolerance.', ['C-029'], ['§6.2'], 'Emerging', ['drum', 'loud', 'control', 'bridge', 'tolerance', 'tolerating', 'banging', 'himself', 'herself']),
  k('K-30', 'Older children and fear of sounds', 'For older children whose fear of sounds causes avoidance, CBT-based approaches from a trained therapist can help.', ['C-030'], ['§6.2'], 'Verified', ['older', 'fear', 'afraid', 'scared', 'avoid', 'avoids', 'avoidance', 'going out', 'year old', 'cbt', 'anxiety', 'teen']),
  k('K-31', 'Safe volume', 'Keep volume moderate and avoid sudden loud sounds. Safe listening guidance is about 85 dB at most, lower for young children. Use headphones made for children that limit volume.', ['C-031'], ['§5', '§7.2'], 'Verified', ['volume', 'db', 'decibel', 'headphones', 'how loud', 'safe level']),
  // --- Unverified therapies
  k('K-32', 'Auditory Integration Training', 'Auditory Integration Training (Berard) has not been shown to work in controlled trials, and major professional bodies do not support it. The app rates it Unverified.', ['C-032'], ['§5'], 'Unverified', ['ait', 'auditory integration', 'berard']),
  k('K-33', 'Tomatis', 'In a small placebo-controlled trial, the Tomatis method did no better than placebo. The app rates it Unverified.', ['C-033'], ['§5'], 'Unverified', ['tomatis']),
  k('K-34', 'Safe and Sound Protocol', 'The Safe and Sound Protocol has no controlled trials in autism, and the theory behind it is contested. It is low risk under a licensed provider, but unproven.', ['C-034'], ['§5'], 'Unverified', ['ssp', 'safe and sound', 'polyvagal']),
  k('K-35', 'Filtered music programmes', 'Samonas, Therapeutic Listening and iLs have no robust controlled trials in autism.', ['C-035'], ['§5'], 'Unverified', ['samonas', 'therapeutic listening', 'ils', 'filtered music']),
  k('K-36', 'Special frequencies', 'Binaural beats and "432 Hz" or "Solfeggio" music have no scientific basis as an autism therapy. They are harmless as relaxing music if your child enjoys it.', ['C-036'], ['§5'], 'Unverified', ['binaural', '432', 'solfeggio', 'frequency', 'frequencies', 'hz']),
  k('K-37', 'Sound baths', 'Sound baths and singing bowls have no evidence as therapy. Some children find them relaxing; others find them overwhelming.', ['C-037'], ['§5'], 'Unverified', ['sound bath', 'singing bowl', 'vibration', 'gong']),
  k('K-38', 'Trying an unproven programme', 'If you choose an unproven programme, set a fixed trial period (for example 8 weeks), agree measurable goals first, and stop if there is no clear change. Be cautious of anyone who makes big promises about autism, sells expensive listening equipment, or discourages other therapies.', ['C-038', 'C-040'], ['§5', '§7.3'], 'Verified', ['unproven', 'try', 'programme', 'program', 'expensive', 'trial period', 'worth it']),
  // --- Therapists
  k('K-39', 'Finding a music therapist', 'Look for a credentialed music therapist (for example MT-BC or HCPC-registered, or your country’s equivalent). Ask about their experience with autistic children, how goals will be measured, whether they will work with your child’s other therapists and school, whether parents can join, and when you will review progress.', ['C-039'], ['§7.3'], 'Verified', ['therapist', 'find', 'choose', 'credential', 'mt-bc', 'hcpc', 'qualified']),
  k('K-40', 'What a course looks like', 'A typical music therapy course is 30–45 minute sessions once or twice a week for 8–20 weeks, with clearly written goals shared with the family.', ['C-041'], ['§2'], 'Verified', ['sessions', 'how often', 'weeks', 'course', 'length', 'cost']),
];

export function passageById(id: string): KnowledgePassage | undefined {
  return KNOWLEDGE.find((p) => p.id === id);
}
