#!/usr/bin/env node
// Builds evidence/claims_register.md and evidence/traceability_matrix.md from the
// canonical JSON files, and scans the repository for REQ-ID references.
// Usage: node scripts/traceability.mjs [--strict]
//   --strict fails if any MVP requirement lacks a code reference or a test reference.
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const strict = process.argv.includes('--strict');
const claimsDoc = JSON.parse(readFileSync(join(root, 'evidence/claims_register.json'), 'utf8'));
const reqDoc = JSON.parse(readFileSync(join(root, 'specs/requirements.json'), 'utf8'));
const claimIds = new Set(claimsDoc.claims.map((c) => c.id));
const errors = [];

// ---- claims register markdown ------------------------------------------------
const esc = (s) => String(s).replace(/\|/g, '\\|');
let md = `# Claims Register\n\n_Generated from \`evidence/claims_register.json\` v${claimsDoc.version} (${claimsDoc.updated}). Do not edit by hand._\n\n`;
md += `**Tier convention:** ${claimsDoc.conventions.tier}\n\n`;
md += '| ID | Claim (user-facing wording) | Tier | Sub-study | Source |\n| --- | --- | --- | --- | --- |\n';
for (const c of claimsDoc.claims) {
  md += `| ${c.id} | ${esc(c.text)} | ${c.tier} | ${c.sections.join(', ')} | ${esc(c.sources.join('; '))} |\n`;
}
md += `\n## Banned claims\n\nTerms: ${claimsDoc.bannedClaims.terms.map((t) => `\`${t}\``).join(', ')}\n\n`;
md += claimsDoc.bannedClaims.rules.map((r) => `- ${r}`).join('\n') + '\n';
writeFileSync(join(root, 'evidence/claims_register.md'), md);

// ---- scan repository for REQ references ------------------------------------------
const SKIP = new Set(['node_modules', '.git', 'dist', 'coverage', 'playwright-report', 'test-results']);
const TEXT = /\.(ts|tsx|js|mjs|json|md|css|html)$/;
function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (SKIP.has(name)) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (TEXT.test(name)) out.push(p);
  }
  return out;
}
const files = walk(root).map((p) => relative(root, p).split(sep).join('/'));
const category = (f) => {
  if (f.startsWith('specs/') || f.startsWith('evidence/') || f.startsWith('decisions/')) return null;
  if (f.startsWith('design/')) return 'design';
  if (f.startsWith('evals/') || f.includes('/evals/')) return 'eval';
  if (/\.(test|spec)\.(ts|tsx|js|mjs)$/.test(f) || f.startsWith('tests/') || f.includes('/e2e/')) return 'test';
  if (f.startsWith('architecture/')) return 'architecture';
  if (f.startsWith('packages/') || f.startsWith('apps/')) return 'code';
  return null;
};
const refs = {};
for (const f of files) {
  const cat = category(f);
  if (!cat) continue;
  const text = readFileSync(join(root, f), 'utf8');
  for (const m of text.matchAll(/REQ-[A-Z0-9]+-\d{2}/g)) {
    ((refs[m[0]] ??= {})[cat] ??= new Set()).add(f);
  }
}

// ---- validate and write matrix -------------------------------------------------
const reqIds = new Set(reqDoc.requirements.map((r) => r.id));
for (const id of Object.keys(refs)) if (!reqIds.has(id)) errors.push(`Unknown requirement referenced: ${id} in ${[...Object.values(refs[id])].flatMap((s) => [...s]).join(', ')}`);
const list = (id, cat) => [...(refs[id]?.[cat] ?? [])].sort();
let tm = `# Traceability Matrix\n\n_Generated by \`npm run trace\` from \`specs/requirements.json\` and a scan of the repository. Do not edit by hand._\n\n`;
tm += '| REQ | Scope | Claims | Design | Architecture | Code | Tests | Evals |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n';
const counts = { mvp: 0, code: 0, test: 0 };
for (const r of reqDoc.requirements) {
  for (const c of r.claims) if (!claimIds.has(c)) errors.push(`${r.id} cites unknown claim ${c}`);
  const functional = /^M\d+$/.test(r.module);
  if (functional && r.scope === 'MVP' && r.claims.length === 0) errors.push(`${r.id} is an MVP functional requirement with no evidence claim`);
  const code = list(r.id, 'code'), test = list(r.id, 'test');
  if (r.scope === 'MVP') {
    counts.mvp++;
    if (code.length) counts.code++; else if (strict) errors.push(`${r.id} has no code reference`);
    if (test.length) counts.test++; else if (strict) errors.push(`${r.id} has no test reference`);
  }
  const fmt = (a) => (a.length ? a.map((x) => `\`${x}\``).join('<br>') : '—');
  tm += `| ${r.id} | ${r.scope} | ${r.claims.join(', ') || '—'} | ${fmt(list(r.id, 'design'))} | ${fmt(list(r.id, 'architecture'))} | ${fmt(code)} | ${fmt(test)} | ${fmt(list(r.id, 'eval'))} |\n`;
}
tm += `\n**Coverage:** ${counts.mvp} MVP requirements · ${counts.code} with code · ${counts.test} with tests.\n`;
writeFileSync(join(root, 'evidence/traceability_matrix.md'), tm);

if (errors.length) {
  console.error('Traceability errors:\n- ' + errors.join('\n- '));
  process.exit(1);
}
console.log(`Traceability OK: ${counts.mvp} MVP reqs, ${counts.code} with code, ${counts.test} with tests.`);
